### PR TITLE
Add guidance on refresh token lifetime, renewal, revocation

### LINKED ISSUE #18: Guidance on Refresh Token Rotation
https://www.rfc-editor.org/rfc/rfc6819.html#section-5.2.2.3 says:

> Refresh token rotation is intended to automatically detect and
> prevent attempts to use the same refresh token in parallel from
> different apps/devices.  This happens if a token gets stolen from the
> client and is subsequently used by both the attacker and the
> legitimate client.  The basic idea is to change the refresh token
> value with every refresh request in order to detect attempts to
> obtain access tokens using old refresh tokens.  Since the
> authorization server cannot determine whether the attacker or the
> legitimate client is trying to access, in case of such an access
> attempt the valid refresh token and the access authorization
> associated with it are both revoked.
> 
> The OAuth specification supports this measure in that the token's
> response allows the authorization server to return a new refresh
> token even for requests with grant type "refresh_token".
> 
> Note: This measure may cause problems in clustered environments,
> since usage of the currently valid refresh token must be ensured.  In
> such an environment, other measures might be more appropriate.

CILogon currently implements this. We've found that some clients ignore the new refresh token and try to keep using the old refresh token, which I believe is a violation of https://www.rfc-editor.org/rfc/rfc6749.html#section-6 which says:

> The authorization server MAY issue a new refresh token, in which case
> the client MUST discard the old refresh token and replace it with the
> new refresh token.  The authorization server MAY revoke the old
> refresh token after issuing a new refresh token to the client.  If a
> new refresh token is issued, the refresh token scope MUST be
> identical to that of the refresh token included by the client in the
> request.

Since I think the IAM default behavior is to never expire refresh tokens, the clients can ignore the new refresh tokens and still work successfully against IAM, which may cause problems when WLCG configures IAM to implement the 30 day maximum lifetime on refresh tokens as specified in the profile.

See the March 2022 thread about "Refresh token lifetime, renewal, revocation" on project-lcg-authz@cern.ch for additional context, including a discussion of current oidc-agent behavior.

It'd be helpful if the profile addressed the following topics:
1. If the token issuer does not implement Refresh Token Rotation, what happens when the refresh token expires in 30 days? Does the client (e.g., robot) need to do a new authorization code flow?
2. If the token issuer implements Refresh Token Rotation, is the new refresh token valid for another 30 days from the date of issuance (i.e., the lifetime of the chain of refresh tokens can be extended indefinitely)?
3. If the token issuer implements Refresh Token Rotation, what happens if the client fails to use the new refresh token and continues to use the old refresh token? Should the refresh tokens be immediately revoked or should there be a grace period (for clustered environments or client-side token synchronization failures)?

### PR DESCRIPTION
**Pull request by jbasney**
resolves #18

### CODE REVIEW

**Comment by jbasney** [comment]
Could we discuss this on the next WLCG AuthZ call, please

**Review by DrDaveD — APPROVED** [review]

**Comment by jbasney** [comment]
Revised based on Sep 30 2022 WLCG AuthZ WG discussion to avoid introducing the new concept of "grace period" and instead simply allow old refresh tokens to expire according to their specified lifetimes.

**Comment by DrDaveD** [comment]
A practical disadvantage of waiting for the entire remaining lifetime before the server discards the old refresh token is that if the client is misconfigured and does not store the new refresh token (for example by not using oidc-agent's `oidc-add --pw-store` option) then they won't know about it until the entire lifetime has passed, which can be up to 30 days.

I think it would be better to mention that it is also RECOMMENDED to reduce the expiration time of the old refresh token after it is replaced, to the lesser of the previous expiration time and 24 hours or some other configurable amount. 

This will also have the advantage as Martin says of much sooner cleaning out what may be a large number of old tokens, assuming they get removed after they expire.  For example I expect that each batch of jobs submitted will be getting a new refresh token every 20 minutes while any of the jobs are running.  I don't know how many batches of jobs typically run continuously on average, but if there are 100 of them, over 30 days that would be over 200,000 refresh tokens.

**Comment by DrDaveD** [comment]
I suggest updating the pull request to state it the way you want it.

**Comment by DrDaveD** [comment]
Looks good to me now.

**Comment by maarten-litmaath** [comment]
LGTM, thanks!

**Review by maarten-litmaath — APPROVED** [review]
LGTM.

**Pull request merged**
